[package]
name = "refact-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
refact-chat-api = { path = "../refact-chat-api" }
refact-core = { path = "../refact-core" }
refact-integrations = { path = "../refact-integrations" }
headless_chrome = "1.0.16"
regex = "1.9.5"
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9.31"
tracing.workspace = true
tungstenite = { version = "0.28", features = ["rustls-tls-native-roots"] }
uuid.workspace = true

[dev-dependencies]
tempfile = "3"
