import type { BuddyAnimState, GroundFX } from "../types";
export declare function spawnSparks(anim: BuddyAnimState, count: number, color?: string): void;
export declare function spawnRainbowSparks(anim: BuddyAnimState, count: number): void;
export declare function spawnFloatingEmoji(anim: BuddyAnimState, emoji: string, x?: number, y?: number, count?: number): void;
export declare function spawnSleepParticle(anim: BuddyAnimState): void;
export declare function spawnOrbitingOrb(anim: BuddyAnimState, emoji: string, count: number): void;
export declare function spawnAfterimage(anim: BuddyAnimState): void;
export declare function spawnSpeedLines(anim: BuddyAnimState, count: number, baseAngle: number, velocityY?: number): void;
export declare function spawnGroundEffect(anim: BuddyAnimState, type: GroundFX["type"], x: number, y: number): void;
export declare function updateAndRenderSparks(ctx: CanvasRenderingContext2D, anim: BuddyAnimState): void;
export declare function updateAndRenderFloatingEmojis(ctx: CanvasRenderingContext2D, anim: BuddyAnimState): void;
export declare function updateAndRenderSleepParticles(ctx: CanvasRenderingContext2D, anim: BuddyAnimState, accentColor: string, frame: number): void;
export declare function updateAndRenderOrbitingOrbs(ctx: CanvasRenderingContext2D, anim: BuddyAnimState): void;
export declare function updateAndRenderAfterimages(ctx: CanvasRenderingContext2D, anim: BuddyAnimState, bodyColor: string): void;
export declare function updateAndRenderSpeedLines(ctx: CanvasRenderingContext2D, anim: BuddyAnimState): void;
export declare function updateAndRenderGroundEffects(ctx: CanvasRenderingContext2D, anim: BuddyAnimState, accentColor: string): void;
