import type { Palette, Stage, SignalDef, SkillDef, ToyDef } from "./types";

export const CANVAS_SIZE = 128;
export const CANVAS_CENTER_X = CANVAS_SIZE / 2;
export const CANVAS_CENTER_Y = CANVAS_SIZE / 2 + 2;

export const PALETTES: Palette[] = [
  {
    name: "Ocean",
    body: "#3B82F6",
    light: "#93C5FD",
    dark: "#1E40AF",
    belly: "#BFDBFE",
    eyeDark: "#1E293B",
    outline: "#1E3A5F",
    rosy: "#F472B6",
    accent: "#60A5FA",
  },
  {
    name: "Forest",
    body: "#22C55E",
    light: "#86EFAC",
    dark: "#15803D",
    belly: "#DCFCE7",
    eyeDark: "#14532D",
    outline: "#14532D",
    rosy: "#FB923C",
    accent: "#4ADE80",
  },
  {
    name: "Sunset",
    body: "#F59E0B",
    light: "#FDE68A",
    dark: "#B45309",
    belly: "#FEF3C7",
    eyeDark: "#78350F",
    outline: "#92400E",
    rosy: "#F87171",
    accent: "#FBBF24",
  },
  {
    name: "Violet",
    body: "#A855F7",
    light: "#D8B4FE",
    dark: "#7E22CE",
    belly: "#F3E8FF",
    eyeDark: "#3B0764",
    outline: "#581C87",
    rosy: "#F472B6",
    accent: "#C084FC",
  },
  {
    name: "Coral",
    body: "#F87171",
    light: "#FECACA",
    dark: "#B91C1C",
    belly: "#FEE2E2",
    eyeDark: "#7F1D1D",
    outline: "#991B1B",
    rosy: "#FB923C",
    accent: "#FCA5A5",
  },
  {
    name: "Mint",
    body: "#2DD4BF",
    light: "#99F6E4",
    dark: "#0F766E",
    belly: "#CCFBF1",
    eyeDark: "#134E4A",
    outline: "#115E59",
    rosy: "#FB923C",
    accent: "#5EEAD4",
  },
  {
    name: "Berry",
    body: "#EC4899",
    light: "#F9A8D4",
    dark: "#BE185D",
    belly: "#FCE7F3",
    eyeDark: "#831843",
    outline: "#9D174D",
    rosy: "#C084FC",
    accent: "#F472B6",
  },
  {
    name: "Storm",
    body: "#94A3B8",
    light: "#CBD5E1",
    dark: "#475569",
    belly: "#E2E8F0",
    eyeDark: "#1E293B",
    outline: "#334155",
    rosy: "#FCA5A5",
    accent: "#94A3B8",
  },
];

export const NAMES = [
  "Mochi",
  "Pixel",
  "Boop",
  "Noodle",
  "Ziggy",
  "Pip",
  "Tofu",
  "Sparky",
  "Blip",
  "Waffle",
  "Glitch",
  "Nimbus",
  "Widget",
  "Cosmo",
  "Qubit",
  "Rune",
  "Byte",
  "Chip",
  "Nova",
  "Ember",
  "Sage",
  "Binx",
  "Gizmo",
  "Dewdrop",
  "Sprocket",
  "Fizz",
  "Rumble",
  "Lint",
  "Flick",
  "Mango",
];

export const STAGES: Stage[] = [
  { name: "Egg", emoji: "🥚", xpThreshold: 0, tagline: "Dormant code seed..." },
  { name: "Hatch", emoji: "🐣", xpThreshold: 30, tagline: "First boot!" },
  {
    name: "Sprite",
    emoji: "👾",
    xpThreshold: 100,
    tagline: "Tiny process running",
  },
  { name: "Imp", emoji: "😈", xpThreshold: 300, tagline: "Mischievous helper" },
  {
    name: "Daemon",
    emoji: "🔥",
    xpThreshold: 700,
    tagline: "Background daemon",
  },
  { name: "Sage", emoji: "🧙", xpThreshold: 1500, tagline: "Project oracle" },
  {
    name: "Archon",
    emoji: "✨",
    xpThreshold: 3000,
    tagline: "Transcended process",
  },
];

export const SIGNALS: Record<string, SignalDef> = {
  user_message: {
    mood: "curious",
    animationType: "perk",
    xp: 2,
    icon: "💬",
    statusTexts: ["Listening...", "Reading msg", "Hmm?"],
    isError: false,
    isWin: true,
  },
  chat_started: {
    mood: "working",
    animationType: "work",
    xp: 3,
    icon: "▶️",
    statusTexts: ["Booting session", "Init chat", "Spawning..."],
    isError: false,
    isWin: true,
  },
  chat_completed: {
    mood: "celebrate",
    animationType: "celebrate",
    xp: 15,
    icon: "✅",
    statusTexts: ["Process complete!", "Exit 0!", "Clean shutdown!"],
    isError: false,
    isWin: true,
  },
  chat_error: {
    mood: "concerned",
    animationType: "shake",
    xp: 1,
    icon: "❌",
    statusTexts: ["SEGFAULT!", "Stack trace...", "Core dumped!"],
    isError: true,
    isWin: false,
  },
  streaming: {
    mood: "focused",
    animationType: "work",
    xp: 1,
    icon: "📡",
    statusTexts: ["stdout flowing...", "Pipe open", "Buffering..."],
    isError: false,
    isWin: false,
  },
  generating: {
    mood: "thinking",
    animationType: "think",
    xp: 1,
    icon: "⚡",
    statusTexts: ["CPU spinning...", "Inference...", "Computing..."],
    isError: false,
    isWin: false,
  },
  tool_used: {
    mood: "working",
    animationType: "work",
    xp: 3,
    icon: "🔧",
    statusTexts: ["Forking tool...", "Subprocess GO", "exec()"],
    isError: false,
    isWin: false,
  },
  tool_failed: {
    mood: "concerned",
    animationType: "shake",
    xp: 1,
    icon: "💥",
    statusTexts: ["SIGKILL!", "Tool panic!", "Retry fork..."],
    isError: true,
    isWin: false,
  },
  tool_confirmation: {
    mood: "alert",
    animationType: "perk",
    xp: 1,
    icon: "⏸️",
    statusTexts: ["Awaiting ACK", "sudo?", "Permission?"],
    isError: false,
    isWin: false,
  },
  edit_applied: {
    mood: "happy",
    animationType: "celebrate",
    xp: 5,
    icon: "📝",
    statusTexts: ["Patched!", "Diff applied", "Write OK"],
    isError: false,
    isWin: true,
  },
  search_done: {
    mood: "curious",
    animationType: "perk",
    xp: 3,
    icon: "🔍",
    statusTexts: ["grep done!", "Match found", "Located!"],
    isError: false,
    isWin: false,
  },
  browser_action: {
    mood: "curious",
    animationType: "perk",
    xp: 3,
    icon: "🌐",
    statusTexts: ["curl -L ...", "Fetching DOM", "Scraping..."],
    isError: false,
    isWin: false,
  },
  title_generating: {
    mood: "thinking",
    animationType: "think",
    xp: 2,
    icon: "📋",
    statusTexts: ["Naming thread...", "Title gen...", "Labeling..."],
    isError: false,
    isWin: false,
  },
  commit_msg: {
    mood: "focused",
    animationType: "work",
    xp: 4,
    icon: "📦",
    statusTexts: ["git commit -m", "Changelog...", "Conventional..."],
    isError: false,
    isWin: false,
  },
  memory_extract: {
    mood: "learning",
    animationType: "absorb",
    xp: 5,
    icon: "🧠",
    statusTexts: ["malloc(memory)", "Caching pattern", "Synapse stored"],
    isError: false,
    isWin: true,
  },
  knowledge_update: {
    mood: "learning",
    animationType: "absorb",
    xp: 5,
    icon: "📚",
    statusTexts: ["Graph update", "Linking nodes", "Knowledge++"],
    isError: false,
    isWin: true,
  },
  indexing: {
    mood: "working",
    animationType: "work",
    xp: 3,
    icon: "📂",
    statusTexts: ["Walking tree...", "Scanning /src", "find . -name"],
    isError: false,
    isWin: false,
  },
  vecdb_building: {
    mood: "focused",
    animationType: "work",
    xp: 4,
    icon: "🧮",
    statusTexts: ["Embedding...", "Vectors...", "Cosine prep"],
    isError: false,
    isWin: false,
  },
  ast_parsing: {
    mood: "focused",
    animationType: "work",
    xp: 4,
    icon: "🌳",
    statusTexts: ["treesitter go", "Parse nodes", "AST walk"],
    isError: false,
    isWin: false,
  },
  compression: {
    mood: "eating",
    animationType: "eat",
    xp: 3,
    icon: "🗜️",
    statusTexts: ["gzip -9", "Deflating...", "Trimming ctx"],
    isError: false,
    isWin: false,
  },
  task_created: {
    mood: "alert",
    animationType: "perk",
    xp: 5,
    icon: "📋",
    statusTexts: ["New PID!", "Task queued", "Job spawned"],
    isError: false,
    isWin: false,
  },
  task_completed: {
    mood: "celebrate",
    animationType: "celebrate",
    xp: 20,
    icon: "🎯",
    statusTexts: ["PID complete!", "Task reaped!", "Victory!"],
    isError: false,
    isWin: true,
  },
  task_failed: {
    mood: "concerned",
    animationType: "shake",
    xp: 2,
    icon: "📋",
    statusTexts: ["Exit 1", "Task zombie", "OOM killed"],
    isError: true,
    isWin: false,
  },
  checkpoint_saved: {
    mood: "happy",
    animationType: "celebrate",
    xp: 4,
    icon: "💾",
    statusTexts: ["Snapshot!", "State saved", "Checkpointed"],
    isError: false,
    isWin: true,
  },
  skill_learned: {
    mood: "celebrate",
    animationType: "celebrate",
    xp: 15,
    icon: "⭐",
    statusTexts: ["Leveled up!", "New syscall!", "Skill get!"],
    isError: false,
    isWin: true,
  },
  balance_low: {
    mood: "concerned",
    animationType: "shake",
    xp: 0,
    icon: "💰",
    statusTexts: ["Low tokens!", "Budget warn!", "Quota low"],
    isError: true,
    isWin: false,
  },
  connection_lost: {
    mood: "concerned",
    animationType: "shake",
    xp: 0,
    icon: "📡",
    statusTexts: ["ECONNREFUSED", "Socket dead", "Ping timeout"],
    isError: true,
    isWin: false,
  },
  connection_restored: {
    mood: "happy",
    animationType: "celebrate",
    xp: 2,
    icon: "📡",
    statusTexts: ["Link up!", "Reconnected!", "Socket OK"],
    isError: false,
    isWin: true,
  },
  git_changes: {
    mood: "alert",
    animationType: "perk",
    xp: 2,
    icon: "🔀",
    statusTexts: ["git diff", "HEAD moved", "New commits"],
    isError: false,
    isWin: false,
  },
  idle_timeout: {
    mood: "sleepy",
    animationType: "sleep",
    xp: 0,
    icon: "😴",
    statusTexts: ["SIGSTOP", "Sleeping...", "Idle..."],
    isError: false,
    isWin: false,
  },
};

export const SKILLS: SkillDef[] = [
  { id: "edit", name: "Code Patching", icon: "📝", xpThreshold: 20 },
  { id: "search", name: "grep Master", icon: "🔍", xpThreshold: 30 },
  { id: "debug", name: "Bug Hunter", icon: "🐛", xpThreshold: 50 },
  { id: "knowledge", name: "Knowledge Graph", icon: "📚", xpThreshold: 60 },
  { id: "browser", name: "Web Crawler", icon: "🌐", xpThreshold: 70 },
  { id: "refactor", name: "Refactoring", icon: "🔄", xpThreshold: 80 },
  { id: "test", name: "Test Runner", icon: "🧪", xpThreshold: 90 },
  { id: "review", name: "Code Review", icon: "👁", xpThreshold: 100 },
  { id: "git", name: "Git Wizard", icon: "🔀", xpThreshold: 110 },
  { id: "arch", name: "Architect", icon: "🏗", xpThreshold: 120 },
  { id: "plan", name: "Task Planner", icon: "📋", xpThreshold: 140 },
  { id: "mem", name: "Memory Daemon", icon: "🧠", xpThreshold: 150 },
];

export const TOY_DEFS: Record<string, ToyDef> = {
  duck: { statusMessage: "quack!", xp: 1 },
  dice: { statusMessage: "01101001!", xp: 2 },
  coffee: { statusMessage: "nom nom~", xp: 0, energyRestore: 22 },
  bug: { statusMessage: "gotcha!", xp: 3 },
  scroll: { statusMessage: "reading...", xp: 2 },
};

export const TOY_EMOJI: Record<string, string> = {
  duck: "🦆",
  dice: "🎲",
  coffee: "☕",
  bug: "🐛",
  scroll: "📜",
};

export const STAGE_SIZES: [number, number][] = [
  [20, 16],
  [20, 23],
  [24, 18],
  [26, 18],
  [28, 18],
  [28, 18],
  [28, 22],
];

export const PERSISTENT_TOY_ACTIONS = new Set([
  "walk",
  "playDuck",
  "playDice",
  "drinkCoffee",
  "playBug",
  "readScroll",
]);
