import { FimDebugData } from '.';
import { ActionCreatorWithoutPayload, ActionCreatorWithPayload } from '@reduxjs/toolkit';
import type { FileInfo } from "../features/Chat/activeFile";
export { type ChatThread, type Chat, type ToolUse, } from "../features/Chat/Thread/types";
export { newChatAction, newChatWithInitialMessages, } from "../features/Chat/Thread/actions";
import { type Chat } from "../features/Chat/Thread/types";
import type { Snippet } from "../features/Chat/selectedSnippet";
import type { Config } from "../features/Config/configSlice";
import type { ErrorSliceState } from "../features/Errors/errorsSlice";
import type { HistoryState } from "../features/History/historySlice";
import type { TipOfTheDayState } from "../features/TipOfTheDay";
import type { PageSliceState } from "../features/Pages/pagesSlice";
import { CurrentProjectInfo } from "../features/Chat/currentProject";
export { updateConfig, type Config } from "../features/Config/configSlice";
export { type FileInfo, setFileInfo } from "../features/Chat/activeFile";
export { type Snippet, setSelectedSnippet, } from "../features/Chat/selectedSnippet";
export type { FimDebugData } from "../services/refact/fim";
export type { ChatHistoryItem } from "../features/History/historySlice";
export { addInputValue, setInputValue } from "../components/ChatForm/actions";
export { setCurrentProjectInfo, type CurrentProjectInfo, } from "../features/Chat/currentProject";
export type { TextDocToolCall } from "../components/Tools/types";
export type { CustomPromptsResponse, CapsResponse, UserMessage, ChatMessage, ChatMessages, DiffChunk, ToolEditResult, } from "../services/refact";
export type InitialState = {
    tipOfTheDay: TipOfTheDayState;
    config: Config;
    active_file: FileInfo;
    selected_snippet: Snippet;
    chat: Chat;
    history: HistoryState;
    error: ErrorSliceState;
    pages: PageSliceState;
    current_project: CurrentProjectInfo;
};
export { ideOpenFile, type OpenFilePayload, ideDiffPasteBackAction, ideNewFileAction, ideOpenHotKeys, ideOpenSettingsAction, ideOpenChatInNewTab, ideOpenChatInBrowser, ideOpenFolderInNewWindow, ideAnimateFileStart, ideAnimateFileStop, ideChatPageChange, ideEscapeKeyPressed, ideIsChatStreaming, ideIsChatReady, ideToolCall, ideToolCallResponse, ideSetCodeCompletionModel, ideSetLoginMessage, ideTaskDone, ideAskQuestions, ideSwitchToThread, } from "../hooks/useEventBusForIDE";
export { ideAttachFileToChat } from "../hooks/useEventBusForApp";
export { toPascalCase } from "../utils/toPascalCase";
export declare const fim: {
    request: ActionCreatorWithoutPayload<"fim/request">;
    ready: ActionCreatorWithoutPayload<"fim/ready">;
    receive: ActionCreatorWithPayload<FimDebugData, string>;
    error: ActionCreatorWithPayload<string, string>;
};
export { isAssistantDelta, isAssistantMessage, isCapsResponse, isChatContextFileDelta, isChatContextFileMessage, isChatResponseChoice, isChatUserMessageResponse, isCommandCompletionResponse, isCommandPreviewResponse, isCustomPromptsResponse, isDetailMessage, isDiffMessage, isDiffResponse, isPlainTextMessage, isPlainTextResponse, isSystemPrompts, isToolCallDelta, isToolCallMessage, isToolMessage, isToolResponse, isUserMessage, } from "../services/refact";
export * from "./setup";
export type * from "./setup";
