import { Dispatch, SetStateAction } from 'react';
import { TransformOptions, HandoffOptions, TransformPreviewResponse, HandoffPreviewResponse } from "../services/refact/trajectory";
export type TrajectoryTab = "compress" | "handoff";
export declare function useTrajectoryOps(): {
    chatId: string;
    activeTab: TrajectoryTab;
    setActiveTab: Dispatch<SetStateAction<TrajectoryTab>>;
    transformOptions: TransformOptions;
    handoffOptions: HandoffOptions;
    transformPreview: TransformPreviewResponse | null;
    handoffPreview: HandoffPreviewResponse | null;
    isPreviewingTransform: boolean;
    isApplyingTransform: boolean;
    isPreviewingHandoff: boolean;
    isApplyingHandoff: boolean;
    handlePreviewTransform: () => Promise<void>;
    handleApplyTransform: () => Promise<boolean>;
    handlePreviewHandoff: () => Promise<void>;
    handleApplyHandoff: () => Promise<boolean>;
    clearPreviews: () => void;
    updateTransformOption: (key: keyof TransformOptions, value: boolean) => void;
    updateHandoffOption: (key: keyof HandoffOptions, value: boolean) => void;
};
