[package]
name = "refact-privacy"
version = "0.1.0"
edition = "2021"

[features]
default = []
test-util = []

[dependencies]
refact-core = { path = "../refact-core" }
dunce = "1.0.5"
glob = "0.3.1"
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = "0.9.31"
tokio.workspace = true
unicode-normalization = "0.1"

[dev-dependencies]
tempfile = { workspace = true }
