export { ActivityRail } from "./ActivityRail";
export { GroupSplitView } from "./GroupSplitView";
export { Dock } from "./Dock";
export { SurfacePane } from "./SurfacePane";
export { TabBar } from "./TabBar";
export { WorkspaceView } from "./WorkspaceView";
export { useAgentsSidebarAutoOpen } from "./useAgentsSidebarAutoOpen";
export * from "./FilesPanel";
export * from "./GitPanel";
export * from "./surfaceKey";
export * from "./workspaceAvailability";
export * from "./workspaceSlice";
